### ISSUE TITLE
Provide Secrets to IDE﻿ not works because multiline is not supoorted

### ISSUE THREAD

**Issue by MCMicS** [JetBrains/marketplace-zip-signer#28]
The documentation says:
> using environment variables provided within the Run/Debug Configuration

https://plugins.jetbrains.com/docs/intellij/plugin-signing.html#provide-secrets-to-ide

This not works because environment variables seems not support multiline values. The pem content is stored without newlines and it fails with:
```
gradle-intellij-plugin :jenkins-control-plugin:signPlugin] Error during Marketplace ZIP Signer CLI execution:
Exception in thread "main" java.lang.NullPointerException: pemObject must not be null
	at org.jetbrains.zip.signer.signer.PrivateKeyUtils.loadKeyPair(PrivateKeyUtils.kt:62)
	at org.jetbrains.zip.signer.signer.PrivateKeyUtils.loadKeyPair(PrivateKeyUtils.kt:48)
	at org.jetbrains.zip.signer.signer.SignerInfoLoader.loadSignerInfoFromText(SignerInfoLoader.kt:30)
	at org.jetbrains.zip.signer.ZipSigningTool.sign(ZipSigningTool.kt:58)
	at org.jetbrains.zip.signer.ZipSigningTool.main(ZipSigningTool.kt:29)
```

**Comment by ekaterina-nikonova** [comment]
In my case, running the command 

```
openssl req\
  -key private.pem\
  -new\
  -x509\
  -days 365\
  -out chain.crt
```

and leaving blank fields (entering `.`) in the certificate request caused this problem. Looks like they all must be non-empty.

**Comment by Konafets** [comment]
I faced the same issue. Is there a workaround to "fix" this?

**Comment by AlexanderPrendota** [comment]
Hi, please vote here: https://youtrack.jetbrains.com/issue/IDEA-185315

**Comment by dinbtechit** [comment]
I'm facing the same issue. Any update on this?
